name: CI-master

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  # First machine, runs Bluepill tests
  build:
    name: Bluepill Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 11.2
      run: sudo xcode-select -s /Applications/Xcode_11.2.app
    - name: Run Bluepill tests
      run: ./scripts/bluepill.sh instance_tests

  # Second machine, runs BP tests and makes build
  build:
    name: BP Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 11.2
      run: sudo xcode-select -s /Applications/Xcode_11.2.app
    - name: Run BP tests
      run: ./scripts/bluepill.sh runner_tests
    - name: Build and Package
      run: ./scripts/bluepill.sh build
