name: CI-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Test and build
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Report event trigger data
      run: |
        echo "Event ${{ github.event_name }}, ref: ${{ github.ref }}"
    - name: Select Xcode 11.1
      run: sudo xcode-select -s /Applications/Xcode_11.1.app
    - name: Run Bluepill tests
      run: ./scripts/bluepill.sh test
    - name: Build Bluepill
      run: ./scripts/bluepill.sh build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'build/*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bazel_build:
    name: Bazel build
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Bazel
        run: brew install bazel
      - name: Build using Bazel
        run: bazel build --host_force_python=PY2 //bluepill:bluepill
